export const defaultBingoOptions = [
  { column: "loldle", title: "loldle", status: false },
  { column: "pokedle", title: "pokedle", status: false },
  { column: "stop_cham", title: "stop cham", status: false },
  { column: "liga_legend", title: "tft/duo/areny", status: false },
  { column: "wyslane_cv", title: "wysłane cv", status: false },
  { column: "dzieki_za_dzisiaj", title: "dzieki za dzisiaj", status: false },
  { column: "szymek_fomo", title: "szymek fomo", status: false },
  { column: "jolie_jolie", title: "jolie jolie", status: false },
  { column: "classcat", title: "classcat", status: false },
  { column: "krecimy", title: "... kręcimy", status: false },
  { column: "tirem", title: "... tirem", status: false },
  { column: "object_object", title: "[Object object]", status: false },
  { column: "stylowanie_buttona", title: "stylowanie buttona", status: false },
  { column: "pisanie_endpointow", title: "pisanie endpointow", status: false },
  {
    column: "daniel_wejdzie_na_disc",
    title: "daniel wejdzie na disc",
    status: false,
  },
  { column: "leakowanie", title: "leakowanie danych", status: false },
  { column: "america", title: "america mentioned 🦅🇺🇸", status: false },
  { column: "odkleja", title: "krzysiu ma odkleje", status: false },
  { column: "patola", title: "patola u daniela", status: false },
  { column: "etaty", title: "5+ etatów", status: false },
  { column: "jesc", title: "... jeść", status: false },
  { column: "obiad", title: "szymek zje ciepły obiad", status: false },
  { column: "skarpeta", title: "skarpeta w gaciach", status: false },
  {
    column: "rostek_jeremi",
    title: "gadanie na rostka/ jeremiego",
    status: false,
  },
];
